image: node:latest

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install -g bower
    - npm i gatsby-cli
    - npm install
    - npx gatsby build
    - ls
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase use canwork-blog
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY